version: 2

before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64

dockers:
  - image_templates:
      - "ghcr.io/fmotalleb/helios-dns:latest"
      - "ghcr.io/fmotalleb/helios-dns:{{ .Major }}"
      - "ghcr.io/fmotalleb/helios-dns:{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/fmotalleb/helios-dns:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
    build_flag_templates:
      - "--pull"
      # OCI annotations: https://github.com/opencontainers/image-spec/blob/main/annotations.md
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
release:
  github:
    name: helios-dns
    owner: fmotalleb
  name_template: "{{.Version}}"
  prerelease: auto
  mode: append
changelog:
  disable: true
